layout: {qmk_keyboard: slicemk_ergodox}
layers:
  default:
  - '&bootloader'
  - ESC
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '-'
  - '='
  - '6'
  - '7'
  - '8'
  - '9'
  - '0'
  - BSPC
  - TAB
  - Q
  - W
  - E
  - R
  - T
  - CAPS
  - {t: numpad, h: numpad}
  - Y
  - U
  - I
  - O
  - P
  - \
  - LCTRL
  - A
  - S
  - D
  - F
  - G
  - H
  - J
  - K
  - L
  - ;
  - ''''
  - LSHFT
  - Z
  - X
  - C
  - V
  - B
  - '['
  - ']'
  - N
  - M
  - ','
  - .
  - /
  - RSHFT
  - ''
  - ''
  - LALT
  - LGUI
  - lower
  - raise
  - media
  - ''
  - ''
  - ''
  - INS
  - HOME
  - PGUP
  - DEL
  - SPACE
  - LCTRL
  - END
  - PGDN
  - Ctl+Alt+ LGUI
  - RET
  - Meh+ LGUI
  - media
  colemak:
  - '&bootloader'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - Q
  - W
  - F
  - P
  - G
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - J
  - L
  - U
  - Y
  - ;
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - A
  - R
  - S
  - T
  - D
  - H
  - N
  - E
  - I
  - O
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - Z
  - X
  - C
  - V
  - B
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - K
  - M
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  numpad:
  - '&bootloader'
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - '7'
  - '8'
  - '9'
  - ''
  - {t: ▽, type: trans}
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {t: numpad, h: toggle, type: held}
  - ''
  - '4'
  - '5'
  - '6'
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - '1'
  - '2'
  - '3'
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - '0'
  - ','
  - .
  - ''
  - ''
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  lower:
  - '&bootloader'
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - F1
  - F2
  - F3
  - F4
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - F5
  - F6
  - F7
  - F8
  - ''
  - LARW
  - DARW
  - UARW
  - RARW
  - ''
  - ''
  - ''
  - F9
  - F10
  - F11
  - F12
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  raise:
  - '&bootloader'
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - '~'
  - '-'
  - '='
  - +
  - '*'
  - /
  - ''
  - ''
  - '|'
  - _
  - '{'
  - '}'
  - \
  - ''
  - ''
  - '`'
  - ''''
  - '"'
  - .
  - ','
  - <
  - '>'
  - (
  - )
  - ':'
  - '?'
  - ''
  - '!'
  - '@'
  - '#'
  - $
  - '%'
  - ''
  - ''
  - ^
  - '&'
  - '['
  - ']'
  - ;
  - ''
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  media:
  - '&bootloader'
  - ''
  - BRI DN
  - BRI UP
  - ''
  - ''
  - ''
  - ''
  - ''
  - {t: BT, h: '0'}
  - {t: BT, h: '1'}
  - {t: BT, h: '2'}
  - {t: BT, h: '3'}
  - {t: BT, h: '4'}
  - OUT TOG
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - OUT USB
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - OUT BLE
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - PREV
  - {t: PP, type: held}
  - NEXT
  - ''
  - BT CLR
  - ''
  - ''
  - ''
  - MUTE
  - ''
  - ''
  - ''
  - ''
  - VOL DN
  - VOL UP
  - ''
  - ''
